#!/usr/bin/env bash
# install nginx server and change landing content
apt-get -y update
apt-get -y install nginx
service nginx start
echo 'Hello World!' | tee /var/www/html/index.html
sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
#sed -i "s|location /redirect_me {|location /redirect_me {\n    rewrite ^/redirect_me\$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;|" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

nginx -t
service nginx restart
