#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get install haproxy=2.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 324403-web-01 52.91.133.43:80 check
   server 324403-web-02 52.87.216.130:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
