#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hosts.new
sed -i "s/.+ localhost$/127.0.0.2 localhost/" ~/hosts.new
sed -i "s/.+ facebook.com$//" ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
